spring.application.name=demo

spring.datasource.url=${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/dnd_cafe}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.MySQLDialect}

server.port=${PORT:8080}

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:dfqmcpdby}
cloudinary.api_key=${CLOUDINARY_API_KEY:639697885611723}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:NEW_SECRET_HERE}